function dataStore = calculateCurrentDisplacement(dataStore, imuParams, sysParams, pointIndex)
    % 计算当前点的位移 - 使用现有的calculateDisplacement函数
    
    if pointIndex > dataStore.window.currentStart
        % 获取当前窗口内的所有数据点
        windowIndices = dataStore.window.currentStart:pointIndex;
        
        % 使用现有的calculateDisplacement函数（改进版本）
        [dispX, dispY, dispZ] = calculateDisplacement(...
            double(dataStore.raw.accelX(windowIndices)), ...
            double(dataStore.raw.accelY(windowIndices)), ...
            double(dataStore.raw.accelZ(windowIndices)), ...
            double(dataStore.compensated.gyroX(windowIndices)), ...
            double(dataStore.compensated.gyroY(windowIndices)), ...
            double(dataStore.compensated.gyroZ(windowIndices)), ...
            dataStore.attitude.pitch(windowIndices), ...
            dataStore.attitude.roll(windowIndices), ...
            sysParams.dt, imuParams.accelRange, imuParams.gyroRange, ...
            dataStore.window.count);
        
        dataStore.displacement.x(pointIndex) = dispX;
        dataStore.displacement.y(pointIndex) = dispY;
        dataStore.displacement.z(pointIndex) = dispZ;
    else
        % 窗口的第一个点，位移为零
        dataStore.displacement.x(pointIndex) = 0;
        dataStore.displacement.y(pointIndex) = 0;
        dataStore.displacement.z(pointIndex) = 0;
    end
end